title: Omotola Musiliu
logo: Headshot.png
description: I am a professional Data Analyst with a solid background in transforming complex data into meaningful insights that support business strategy and performance improvement. I specialize in Excel automation, SQL querying, and Power BI dashboard development—tools I use extensively to streamline data processes and uncover trends that inform decision-making.
With a passion for storytelling through data, I bring a results-driven approach to every project. I am skilled at building robust data models, designing visually compelling reports, and translating technical findings into clear business language for stakeholders at all levels. My work combines both analytical thinking and creative problem-solving, ensuring that every insight delivers measurable value.
I am confident in building end-to-end data solutions from data extraction and transformation to visualization and insight communication. Whether analysing turnover trends, customer behavior, operational performance, or building KPI-driven dashboards, I consistently aim for clarity, efficiency, and impact.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal










