title: Omotola Musiliu
logo: Headshot.jpeg
description: I am a Data Analyst with extensive skills in excel automation, SQL Querying and Power BI for insighht generation.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal










