title: Omotola Musiliu 
logo: Headshot.png
description: I am a professional Data Analyst with a solid background in transforming complex data into meaningful insights that support business strategy and performance improvement. I specialize in Excel automation, SQL querying, and Power BI dashboard development—tools I use extensively to streamline data processes and uncover trends that inform decision-making.
#show downloads: true
#data analytics
theme: jekyll-theme-minimal











