title: Omotola Musiliu 
logo: Headshot.jpg
description: "I am a professional Data Analyst with a solid background in transforming complex data into meaningful insights that support business strategy and performance improvement. I specialize in Excel automation, SQL querying, and Power BI dashboard development—tools I use extensively to streamline data processes and uncover trends that inform decision-making. With a passion for storytelling through data, I bring a results-driven approach to every project"
theme: jekyll-theme-minimal











