title: Omotola Musiliu 
logo: Headshot.png
description: I am a professional Data Analyst with a solid background in transforming complex data into meaningful insights that support business strategy and performance improvement. I specialize in Excel automation, SQL querying, and Power BI dashboard development—tools I use extensively to streamline data processes and uncover trends that inform decision-making.
With a passion for storytelling through data, I bring a results-driven approach to every project. I am skilled at building robust data models, designing visually compelling reports, and translating technical findings into clear business language for stakeholders at all levels.
I am continuously learning and expanding my skillset, staying current with modern data tools and trends. I am also enthusiastic about collaborative problem-solving and thrive in cross-functional teams where I can share ideas with like-minded professionals.
#show downloads: true
#data analytics
theme: jekyll-theme-minimal











